/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LearnRHFRouteImport } from './routes/learnRHF'
import { Route as AboutRouteImport } from './routes/about'
import { Route as TESTRouteImport } from './routes/TEST'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseIndexRouteImport } from './routes/course/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as CourseCourseIdIndexRouteImport } from './routes/course/$courseId/index'
import { Route as AdminCourseIndexRouteImport } from './routes/admin/course/index'
import { Route as AdminCourseCreateRouteImport } from './routes/admin/course/create'
import { Route as AdminCourseCourseIdUpdateRouteImport } from './routes/admin/course/$courseId/update'
import { Route as CourseCourseIdModulesModulesIdIndexRouteImport } from './routes/course/$courseId/modules/$modulesId/index'
import { Route as AdminCourseCourseIdModulesCreateRouteImport } from './routes/admin/course/$courseId/modules/create'
import { Route as CourseCourseIdModulesModulesIdLessonsLessonIdRouteImport } from './routes/course/$courseId/modules/$modulesId/lessons/$lessonId'
import { Route as AdminCourseCourseIdModulesModulesIdUpdateRouteImport } from './routes/admin/course/$courseId/modules/$modulesId/update'
import { Route as AdminCourseCourseIdModulesModulesIdLessonsCreateRouteImport } from './routes/admin/course/$courseId/modules/$modulesId/lessons/create'
import { Route as AdminCourseCourseIdModulesModulesIdLessonsLessonIdUpdateRouteImport } from './routes/admin/course/$courseId/modules/$modulesId/lessons/$lessonId/update'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRHFRoute = LearnRHFRouteImport.update({
  id: '/learnRHF',
  path: '/learnRHF',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TESTRoute = TESTRouteImport.update({
  id: '/TEST',
  path: '/TEST',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdIndexRoute = CourseCourseIdIndexRouteImport.update({
  id: '/course/$courseId/',
  path: '/course/$courseId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCourseIndexRoute = AdminCourseIndexRouteImport.update({
  id: '/admin/course/',
  path: '/admin/course/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCourseCreateRoute = AdminCourseCreateRouteImport.update({
  id: '/admin/course/create',
  path: '/admin/course/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCourseCourseIdUpdateRoute =
  AdminCourseCourseIdUpdateRouteImport.update({
    id: '/admin/course/$courseId/update',
    path: '/admin/course/$courseId/update',
    getParentRoute: () => rootRouteImport,
  } as any)
const CourseCourseIdModulesModulesIdIndexRoute =
  CourseCourseIdModulesModulesIdIndexRouteImport.update({
    id: '/course/$courseId/modules/$modulesId/',
    path: '/course/$courseId/modules/$modulesId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCourseCourseIdModulesCreateRoute =
  AdminCourseCourseIdModulesCreateRouteImport.update({
    id: '/admin/course/$courseId/modules/create',
    path: '/admin/course/$courseId/modules/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const CourseCourseIdModulesModulesIdLessonsLessonIdRoute =
  CourseCourseIdModulesModulesIdLessonsLessonIdRouteImport.update({
    id: '/course/$courseId/modules/$modulesId/lessons/$lessonId',
    path: '/course/$courseId/modules/$modulesId/lessons/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCourseCourseIdModulesModulesIdUpdateRoute =
  AdminCourseCourseIdModulesModulesIdUpdateRouteImport.update({
    id: '/admin/course/$courseId/modules/$modulesId/update',
    path: '/admin/course/$courseId/modules/$modulesId/update',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCourseCourseIdModulesModulesIdLessonsCreateRoute =
  AdminCourseCourseIdModulesModulesIdLessonsCreateRouteImport.update({
    id: '/admin/course/$courseId/modules/$modulesId/lessons/create',
    path: '/admin/course/$courseId/modules/$modulesId/lessons/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCourseCourseIdModulesModulesIdLessonsLessonIdUpdateRoute =
  AdminCourseCourseIdModulesModulesIdLessonsLessonIdUpdateRouteImport.update({
    id: '/admin/course/$courseId/modules/$modulesId/lessons/$lessonId/update',
    path: '/admin/course/$courseId/modules/$modulesId/lessons/$lessonId/update',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/TEST': typeof TESTRoute
  '/about': typeof AboutRoute
  '/learnRHF': typeof LearnRHFRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/course': typeof CourseIndexRoute
  '/admin/course/create': typeof AdminCourseCreateRoute
  '/admin/course': typeof AdminCourseIndexRoute
  '/course/$courseId': typeof CourseCourseIdIndexRoute
  '/admin/course/$courseId/update': typeof AdminCourseCourseIdUpdateRoute
  '/admin/course/$courseId/modules/create': typeof AdminCourseCourseIdModulesCreateRoute
  '/course/$courseId/modules/$modulesId': typeof CourseCourseIdModulesModulesIdIndexRoute
  '/admin/course/$courseId/modules/$modulesId/update': typeof AdminCourseCourseIdModulesModulesIdUpdateRoute
  '/course/$courseId/modules/$modulesId/lessons/$lessonId': typeof CourseCourseIdModulesModulesIdLessonsLessonIdRoute
  '/admin/course/$courseId/modules/$modulesId/lessons/create': typeof AdminCourseCourseIdModulesModulesIdLessonsCreateRoute
  '/admin/course/$courseId/modules/$modulesId/lessons/$lessonId/update': typeof AdminCourseCourseIdModulesModulesIdLessonsLessonIdUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/TEST': typeof TESTRoute
  '/about': typeof AboutRoute
  '/learnRHF': typeof LearnRHFRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/course': typeof CourseIndexRoute
  '/admin/course/create': typeof AdminCourseCreateRoute
  '/admin/course': typeof AdminCourseIndexRoute
  '/course/$courseId': typeof CourseCourseIdIndexRoute
  '/admin/course/$courseId/update': typeof AdminCourseCourseIdUpdateRoute
  '/admin/course/$courseId/modules/create': typeof AdminCourseCourseIdModulesCreateRoute
  '/course/$courseId/modules/$modulesId': typeof CourseCourseIdModulesModulesIdIndexRoute
  '/admin/course/$courseId/modules/$modulesId/update': typeof AdminCourseCourseIdModulesModulesIdUpdateRoute
  '/course/$courseId/modules/$modulesId/lessons/$lessonId': typeof CourseCourseIdModulesModulesIdLessonsLessonIdRoute
  '/admin/course/$courseId/modules/$modulesId/lessons/create': typeof AdminCourseCourseIdModulesModulesIdLessonsCreateRoute
  '/admin/course/$courseId/modules/$modulesId/lessons/$lessonId/update': typeof AdminCourseCourseIdModulesModulesIdLessonsLessonIdUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/TEST': typeof TESTRoute
  '/about': typeof AboutRoute
  '/learnRHF': typeof LearnRHFRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/course/': typeof CourseIndexRoute
  '/admin/course/create': typeof AdminCourseCreateRoute
  '/admin/course/': typeof AdminCourseIndexRoute
  '/course/$courseId/': typeof CourseCourseIdIndexRoute
  '/admin/course/$courseId/update': typeof AdminCourseCourseIdUpdateRoute
  '/admin/course/$courseId/modules/create': typeof AdminCourseCourseIdModulesCreateRoute
  '/course/$courseId/modules/$modulesId/': typeof CourseCourseIdModulesModulesIdIndexRoute
  '/admin/course/$courseId/modules/$modulesId/update': typeof AdminCourseCourseIdModulesModulesIdUpdateRoute
  '/course/$courseId/modules/$modulesId/lessons/$lessonId': typeof CourseCourseIdModulesModulesIdLessonsLessonIdRoute
  '/admin/course/$courseId/modules/$modulesId/lessons/create': typeof AdminCourseCourseIdModulesModulesIdLessonsCreateRoute
  '/admin/course/$courseId/modules/$modulesId/lessons/$lessonId/update': typeof AdminCourseCourseIdModulesModulesIdLessonsLessonIdUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/TEST'
    | '/about'
    | '/learnRHF'
    | '/profile'
    | '/ranking'
    | '/auth/login'
    | '/auth/register'
    | '/course'
    | '/admin/course/create'
    | '/admin/course'
    | '/course/$courseId'
    | '/admin/course/$courseId/update'
    | '/admin/course/$courseId/modules/create'
    | '/course/$courseId/modules/$modulesId'
    | '/admin/course/$courseId/modules/$modulesId/update'
    | '/course/$courseId/modules/$modulesId/lessons/$lessonId'
    | '/admin/course/$courseId/modules/$modulesId/lessons/create'
    | '/admin/course/$courseId/modules/$modulesId/lessons/$lessonId/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/TEST'
    | '/about'
    | '/learnRHF'
    | '/profile'
    | '/ranking'
    | '/auth/login'
    | '/auth/register'
    | '/course'
    | '/admin/course/create'
    | '/admin/course'
    | '/course/$courseId'
    | '/admin/course/$courseId/update'
    | '/admin/course/$courseId/modules/create'
    | '/course/$courseId/modules/$modulesId'
    | '/admin/course/$courseId/modules/$modulesId/update'
    | '/course/$courseId/modules/$modulesId/lessons/$lessonId'
    | '/admin/course/$courseId/modules/$modulesId/lessons/create'
    | '/admin/course/$courseId/modules/$modulesId/lessons/$lessonId/update'
  id:
    | '__root__'
    | '/'
    | '/TEST'
    | '/about'
    | '/learnRHF'
    | '/profile'
    | '/ranking'
    | '/auth/login'
    | '/auth/register'
    | '/course/'
    | '/admin/course/create'
    | '/admin/course/'
    | '/course/$courseId/'
    | '/admin/course/$courseId/update'
    | '/admin/course/$courseId/modules/create'
    | '/course/$courseId/modules/$modulesId/'
    | '/admin/course/$courseId/modules/$modulesId/update'
    | '/course/$courseId/modules/$modulesId/lessons/$lessonId'
    | '/admin/course/$courseId/modules/$modulesId/lessons/create'
    | '/admin/course/$courseId/modules/$modulesId/lessons/$lessonId/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TESTRoute: typeof TESTRoute
  AboutRoute: typeof AboutRoute
  LearnRHFRoute: typeof LearnRHFRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CourseIndexRoute: typeof CourseIndexRoute
  AdminCourseCreateRoute: typeof AdminCourseCreateRoute
  AdminCourseIndexRoute: typeof AdminCourseIndexRoute
  CourseCourseIdIndexRoute: typeof CourseCourseIdIndexRoute
  AdminCourseCourseIdUpdateRoute: typeof AdminCourseCourseIdUpdateRoute
  AdminCourseCourseIdModulesCreateRoute: typeof AdminCourseCourseIdModulesCreateRoute
  CourseCourseIdModulesModulesIdIndexRoute: typeof CourseCourseIdModulesModulesIdIndexRoute
  AdminCourseCourseIdModulesModulesIdUpdateRoute: typeof AdminCourseCourseIdModulesModulesIdUpdateRoute
  CourseCourseIdModulesModulesIdLessonsLessonIdRoute: typeof CourseCourseIdModulesModulesIdLessonsLessonIdRoute
  AdminCourseCourseIdModulesModulesIdLessonsCreateRoute: typeof AdminCourseCourseIdModulesModulesIdLessonsCreateRoute
  AdminCourseCourseIdModulesModulesIdLessonsLessonIdUpdateRoute: typeof AdminCourseCourseIdModulesModulesIdLessonsLessonIdUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learnRHF': {
      id: '/learnRHF'
      path: '/learnRHF'
      fullPath: '/learnRHF'
      preLoaderRoute: typeof LearnRHFRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TEST': {
      id: '/TEST'
      path: '/TEST'
      fullPath: '/TEST'
      preLoaderRoute: typeof TESTRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/': {
      id: '/course/'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId/': {
      id: '/course/$courseId/'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/course/': {
      id: '/admin/course/'
      path: '/admin/course'
      fullPath: '/admin/course'
      preLoaderRoute: typeof AdminCourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/course/create': {
      id: '/admin/course/create'
      path: '/admin/course/create'
      fullPath: '/admin/course/create'
      preLoaderRoute: typeof AdminCourseCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/course/$courseId/update': {
      id: '/admin/course/$courseId/update'
      path: '/admin/course/$courseId/update'
      fullPath: '/admin/course/$courseId/update'
      preLoaderRoute: typeof AdminCourseCourseIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId/modules/$modulesId/': {
      id: '/course/$courseId/modules/$modulesId/'
      path: '/course/$courseId/modules/$modulesId'
      fullPath: '/course/$courseId/modules/$modulesId'
      preLoaderRoute: typeof CourseCourseIdModulesModulesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/course/$courseId/modules/create': {
      id: '/admin/course/$courseId/modules/create'
      path: '/admin/course/$courseId/modules/create'
      fullPath: '/admin/course/$courseId/modules/create'
      preLoaderRoute: typeof AdminCourseCourseIdModulesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId/modules/$modulesId/lessons/$lessonId': {
      id: '/course/$courseId/modules/$modulesId/lessons/$lessonId'
      path: '/course/$courseId/modules/$modulesId/lessons/$lessonId'
      fullPath: '/course/$courseId/modules/$modulesId/lessons/$lessonId'
      preLoaderRoute: typeof CourseCourseIdModulesModulesIdLessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/course/$courseId/modules/$modulesId/update': {
      id: '/admin/course/$courseId/modules/$modulesId/update'
      path: '/admin/course/$courseId/modules/$modulesId/update'
      fullPath: '/admin/course/$courseId/modules/$modulesId/update'
      preLoaderRoute: typeof AdminCourseCourseIdModulesModulesIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/course/$courseId/modules/$modulesId/lessons/create': {
      id: '/admin/course/$courseId/modules/$modulesId/lessons/create'
      path: '/admin/course/$courseId/modules/$modulesId/lessons/create'
      fullPath: '/admin/course/$courseId/modules/$modulesId/lessons/create'
      preLoaderRoute: typeof AdminCourseCourseIdModulesModulesIdLessonsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/course/$courseId/modules/$modulesId/lessons/$lessonId/update': {
      id: '/admin/course/$courseId/modules/$modulesId/lessons/$lessonId/update'
      path: '/admin/course/$courseId/modules/$modulesId/lessons/$lessonId/update'
      fullPath: '/admin/course/$courseId/modules/$modulesId/lessons/$lessonId/update'
      preLoaderRoute: typeof AdminCourseCourseIdModulesModulesIdLessonsLessonIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TESTRoute: TESTRoute,
  AboutRoute: AboutRoute,
  LearnRHFRoute: LearnRHFRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CourseIndexRoute: CourseIndexRoute,
  AdminCourseCreateRoute: AdminCourseCreateRoute,
  AdminCourseIndexRoute: AdminCourseIndexRoute,
  CourseCourseIdIndexRoute: CourseCourseIdIndexRoute,
  AdminCourseCourseIdUpdateRoute: AdminCourseCourseIdUpdateRoute,
  AdminCourseCourseIdModulesCreateRoute: AdminCourseCourseIdModulesCreateRoute,
  CourseCourseIdModulesModulesIdIndexRoute:
    CourseCourseIdModulesModulesIdIndexRoute,
  AdminCourseCourseIdModulesModulesIdUpdateRoute:
    AdminCourseCourseIdModulesModulesIdUpdateRoute,
  CourseCourseIdModulesModulesIdLessonsLessonIdRoute:
    CourseCourseIdModulesModulesIdLessonsLessonIdRoute,
  AdminCourseCourseIdModulesModulesIdLessonsCreateRoute:
    AdminCourseCourseIdModulesModulesIdLessonsCreateRoute,
  AdminCourseCourseIdModulesModulesIdLessonsLessonIdUpdateRoute:
    AdminCourseCourseIdModulesModulesIdLessonsLessonIdUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
